name: inline-js
version: 0.0.1.0
category: Web
maintainer: Cheng Shao <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD-3-Clause
github: tweag/inline-js
synopsis: Call JavaScript from Haskell.
description: Please see <https://github.com/tweag/inline-js> for details.

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.12 && < 5
  - bytestring
  - containers
  - inline-js-core
  - language-javascript
  - syb
  - template-haskell

library:
  source-dirs: src
  generated-other-modules:
    - Paths_inline_js
  exposed-modules:
    - Language.JavaScript.Inline
    - Language.JavaScript.Inline.Aeson
    - Language.JavaScript.Inline.JSParse
    - Language.JavaScript.Inline.TH
